# Generated by Django 3.1.2 on 2020-10-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
